reedmanage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view, login_view, signup

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('signup', signup, name='signup'),
    path('login', login_view, name='login'),
    #path('evaluate/', include('reedsdata.urls', namespace='reeds')),
    path('reeds/', include('reedsdata.urls', namespace='reeds')),
    path('top/', include('usersettings.urls', namespace='setting')),
    path("__reload__/", include("django_browser_reload.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

reedsdata/urls.py
from django.urls import path
from .views import data_entry, reedsdata_list, edit_reedsdata, delete_reedsdata

#from .views import ReedsdataListView, ReedsdataCreateView, ReedsdataUpdateView, ReedsdataDeleteView

app_name = 'reeds'

urlpatterns = [
    path('add/', data_entry, name='add'),
    path('list/', reedsdata_list, name='reedsdata_list'),
    path('edit/<int:pk>/', edit_reedsdata, name='edit_reedsdata'),
    path('delete/<int:pk>/', delete_reedsdata, name='delete_reedsdata'),
]

reedsdata/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here.
class Reedsdata(models.Model):
    CHOICES = [(i, i) for i in range(11)]
    evaluation = models.IntegerField(choices=CHOICES, blank=True, null=True)
    reed_ID = models.CharField(null=True, max_length=220)

    def __str__(self):
        return self.reed_ID

    cane_brand = models.CharField(null=True,
                                  blank=True,
                                  max_length=220,
                                  default=None)
    gouging_machine = models.CharField(null=True, blank=True, max_length=220)
    #date = models.DateTimeField(auto_now_add=True)
    cane_diamater = models.IntegerField(null=True, blank=True, default=None)
    thicness = models.FloatField(null=True, blank=True, default=None)
    hardness = models.FloatField(null=True, blank=True, default=None)
    flexibility = models.FloatField(null=True, blank=True, default=None)
    density = models.FloatField(null=True, blank=True, default=None)
    reedauthor = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now)
    shaper = models.CharField(null=True,
                              blank=True,
                              max_length=220,
                              default=None)
    harvest_year = models.CharField(null=True,
                                    blank=True,
                                    max_length=220,
                                    default=None)
    temperature = models.FloatField(null=True, blank=True, default=None)
    humidity = models.FloatField(null=True, blank=True, default=None)

    class Meta:
        unique_together = ['reed_ID', 'reedauthor']

    def get_fields(self):
        return [(field.name, getattr(self, field.name))
                for field in Reedsdata._meta.fields]

reedsdata/forms.py
from operator import methodcaller
from django import forms
from .models import Reedsdata
from usersettings.models import Checkbox_for_setting


######################################completed###############################
class ViewUser:

    def __init__(self, user):
        self.current_user = user

    def get_field_list(self):
        try:
            data = Checkbox_for_setting.objects.get(user=self.current_user)
            l = data.checkboxsetting
            l = 'reed_ID,' + l + 'evaluation'
            print(l)
            return l
        except Checkbox_for_setting.DoesNotExist:
            return []


class Caneform(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        if user:
            li = ViewUser(user).get_field_list()
            for field_name in list(self.fields):
                if field_name not in li:
                    self.fields.pop(field_name)

    class Meta:
        model = Reedsdata
        fields = '__all__'


#######################################################

reedsdata/views.py
from django.shortcuts import render
from .models import Reedsdata
import pandas as pd
from .forms import Caneform, ViewUser
from usersettings.models import Checkbox_for_setting
from django.views.generic import ListView
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required


# Create your views here.
class ReedsdataListView(ListView):
    model = Reedsdata
    template_name = 'reeddata_list.html'  # Customize this
    context_object_name = 'reed_list'

    def get_queryset(self):
        return Reedsdata.objects.filter(user=self.request.user)


#def chart_select_view(request):
#    #rd1 = pd.DataFrame(Reedsdata.objects.all().values())
#    rd1 = pd.DataFrame(
#        Reedsdata.objects.filter(reedauthor=request.user).values())
#    rd1 = rd1.replace(['NaN', 'None', ''], float('nan'))
#    rd1 = rd1.dropna(how='all')
#    print(rd1)
#
#    context = {
#        'reedeval': rd1.to_html,
#    }
#
#    return render(request, 'reedsdata/edit.html', context)


def data_entry(request):
    form = Caneform(request.POST, user=request.user)
    if form.is_valid():
        obj = form.save(commit=False)
        obj.reedauthor = request.user
        obj.save()
        form = Caneform(user=request.user)

    context = {
        'form': form,
    }
    return render(request, 'reedsdata/add.html', context)


#!!!!!!ORIGINAL!!!!
#def data_entry(request):
#    form = Caneform(request.POST or None)
#    if form.is_valid():
#        obj = form.save(commit=False)
#        obj.reedauthor = request.user
#        obj.save()
#    context = {
#        'form': form,
#    }
#    return render(request, 'reedsdata/add.html', context)
#


@login_required
def reedsdata_list(request):
    reeds = Reedsdata.objects.filter(reedauthor=request.user).order_by('-date')
    return render(request, 'reedsdata/reedsdata_list.html', {'reeds': reeds})


@login_required
def edit_reedsdata(request, pk):
    instance = get_object_or_404(Reedsdata, pk=pk, reedauthor=request.user)

    if request.method == 'POST':
        form = Caneform(request.POST, instance=instance, user=request.user)
        if form.is_valid():
            form.save()
            return redirect('reeds:reedsdata_list')
    else:
        form = Caneform(instance=instance, user=request.user)

    return render(request, 'reedsdata/edit_reedsdata.html', {'form': form})


@login_required
def delete_reedsdata(request, pk):
    instance = get_object_or_404(Reedsdata, pk=pk, reedauthor=request.user)
    if request.method == 'POST':
        instance.delete()
        return redirect('reedsdata_list')
    return render(request, 'reedsdata/confirm_delete.html',
                  {'object': instance})

reedsdata/templates/reedsdata/add.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}Data Entry{% endblock title %}
{% block content %}

<!DOCTYPE html>
     
<body class="bg-gradient-to-r from-indigo-800 to-blue-900 flex items-center justify-center min-h-screen p-8">
    <div class="cursor-pointer block group relative z-50 group bg-white px-6 pt-10 pb-8 shadow-2xl ring-1 ring-gray-900/5 max-w-md w-full rounded-xl sm:px-10 after:h-[1px] after:w-[200px] after:bg-gradient-to-r after:from-transparent after:via-purple-500 after:to-transparent after:absolute after:-top-[2px] after:left-[65%] after:opacity-0 after:content-[''] hover:after:left-[30%] hover:after:opacity-100  after:transition-all animate-fade-in">
        <h2 class="text-2xl font-bold text-center text-indigo-800 mb-8">Data Entry</h2>
        <form action="" method="POST" id="registrationForm" class="space-y-6" >
        <div class="grid grid-cols-1 grid-cols-2 gap-8">
    {% csrf_token %}

    {% for field in form %}
    <div class="mb-4">
        <label for="{{ field.id_for_label }}" class="block text-indigo-900 font-semibold mb-2">
            {{ field.label }}
        </label>
        {{ field|add_class:"w-full px-4 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-800 transition-all duration-300" }}
        
        {% if field.errors %}
            <p class="text-sm text-red-600 mt-1">{{ field.errors }}</p>
        {% endif %}
    </div>
    {% endfor %}
    <br>
    <button type="submit" class="w-full bg-indigo-800 text-white py-3 rounded-lg font-semibold hover:bg-blue-900 focus:outline-none focus:ring-2 focus:ring-indigo-800 focus:ring-offset-2 transition-all duration-300 transform hover:scale-[1.02]">Submit</button>
        </form>
      </div>
       <!-- <p class="text-center text-gray-600 mt-6">
            Already have an account? 
            <a href="https://tailwindflex.com/@nejaa-badr/login-form-12" class="text-indigo-800 font-semibold hover:text-blue-900 transition-colors duration-300">Sign In</a>
        </p>-->


</body>
</html>

{% endblock content %}

reedsdata/templates/reedsdata/confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="max-w-md mx-auto p-6 bg-white shadow rounded text-center">
    <h2 class="text-xl font-bold text-red-600 mb-4">Confirm Delete</h2>
    <p class="mb-6">Are you sure you want to delete <strong>{{ object.reed_ID }}</strong>?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="bg-red-600 text-white px-4 py-2 rounded hover:bg-red-700">Yes, Delete</button>
        <a href="{% url 'reeds:reedsdata_list' %}" class="ml-4 text-gray-700 hover:underline">Cancel</a>
    </form>
</div>
{% endblock %}

reedsdata/templates/reedsdata/edit_reedsdata.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
<body class="bg-gradient-to-r from-indigo-800 to-blue-900 flex items-center justify-center min-h-screen p-8">
    <div class="cursor-pointer block group relative z-50 group bg-white px-6 pt-10 pb-8 shadow-2xl ring-1 ring-gray-900/5 max-w-md w-full rounded-xl sm:px-10 after:h-[1px] after:w-[200px] after:bg-gradient-to-r after:from-transparent after:via-purple-500 after:to-transparent after:absolute after:-top-[2px] after:left-[65%] after:opacity-0 after:content-[''] hover:after:left-[30%] hover:after:opacity-100  after:transition-all animate-fade-in">
        <h2 class="text-2xl font-bold text-center text-indigo-800 mb-8">Edit Reed Data</h2>

    <form method="post" class="space-y-4">
    <div class="grid grid-cols-1 grid-cols-2 gap-8">
        {% csrf_token %}
        {% for field in form.visible_fields %}
        <div>
            <label class="block font-semibold text-indigo-900 mb-1">{{ field.label }}</label>
            {{ field|add_class:"w-full px-4 py-2 border rounded-lg" }}
            {% if field.errors %}
                <p class="text-red-600 text-sm">{{ field.errors }}</p>
            {% endif %}
        </div>
        {% endfor %}
        <br>
<div class="flex justify-between items-center space-x-4">
    <button type="submit" class="bg-indigo-600 text-white px-4 py-2 rounded hover:bg-indigo-700">
        Update
    </button>
    <a href="{% url 'reeds:delete_reedsdata' form.instance.pk %}" class="bg-red-600 text-white px-4 py-2 rounded hover:bg-red-700">
        Delete
    </a>
    <a href="{% url 'reeds:reedsdata_list' %}" class="bg-gray-300 text-gray-800 py-2 px-4 rounded hover:bg-gray-400 transition">
        Cancel
    </a>
</div>
    </div>
    </form>
</div>
{% endblock %}

reedsdata/templates/reedsdata/main.html
{% extends 'base.html' %}
{% block title %}Reed Evaluate{% endblock title %}
{% block content %}
<head>
    <h1> Reed Evaluation </h1>
</head>
{{ reedeval | safe}}
{% endblock content %}

reedsdata/templates/reedsdata/reedsdata_list.html
{% extends 'base.html' %}

{% block content %}
<body class="bg-gradient-to-r from-indigo-800 to-blue-900 flex items-center justify-center min-h-screen p-8">
  <div class="w-full max-w-6xl bg-white px-6 pt-10 pb-8 shadow-2xl ring-1 ring-gray-900/5 rounded-xl sm:px-10 animate-fade-in relative after:h-[1px] after:w-[200px] after:bg-gradient-to-r after:from-transparent after:via-purple-500 after:to-transparent after:absolute after:-top-[2px] after:left-[65%] after:opacity-0 after:content-[''] hover:after:left-[30%] hover:after:opacity-100 after:transition-all">
    
    <h2 class="text-2xl font-bold text-center text-indigo-800 mb-8">My Reeds Data</h2>

    <div class="overflow-x-auto">
      <table class="min-w-full bg-white border rounded-lg shadow">
        <thead class="bg-indigo-100">
          <tr>
            <th class="py-2 px-4 text-left">Reed ID</th>
            <th class="py-2 px-4 text-left">Evaluation</th>
            <th class="py-2 px-4 text-left">Created Date</th>
            <th class="py-2 px-4 text-left">Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for reed in reeds %}
          <tr class="border-t">
            <td class="py-2 px-4">{{ reed.reed_ID }}</td>
            <td class="py-2 px-4">{{ reed.evaluation }}</td>
            <td class="py-2 px-4">{{ reed.date|date:"d M Y" }}</td>
            <td class="py-2 px-4 space-x-2">
              <a href="{% url 'reeds:edit_reedsdata' reed.pk %}" class="text-blue-600 hover:underline">Edit</a>
              <a href="{% url 'reeds:delete_reedsdata' reed.pk %}" class="text-red-600 hover:underline">Delete</a>
            </td>
          </tr>
          {% empty %}
          <tr>
            <td colspan="4" class="py-4 text-center text-gray-600">No reeds found.</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    
  </div>
</body>
{% endblock %}